name: Starling Documentation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.3.7
    - name: Set up Haxelib dependencies
      run: |
        haxelib --global update haxelib --quiet
        haxelib fixrepo --quiet
        haxelib install lime --quiet
        haxelib install openfl --quiet
    - name: Build project
      run: |
        git clone "https://github.com/openfl/starling/"
        cd starling/scripts
        haxe docs.hxml
        cp -r ../docs/ ../../docs
        cd ../..

    - name: Commit compiled files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Actions"
        git add docs
        git commit -m "Compiled files [skip ci]"
        git push

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/
